/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiNetbean;

import Controller.ChuyenManHinhController;
import GUI.GuiAdmin;
import Storage.Account;
import Storage.AccountList;
import java.time.LocalDate;
import java.time.Month;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class guiAdmin extends javax.swing.JFrame {

   // JFrame f;

    /**
     * Creates new form guiAdmin
     */
    public guiAdmin(Account login) {
        initComponents();

        setTitle("Admin");


        
        
//        final DefaultTableModel model = (DefaultTableModel) jt.getModel();
//        AccountList a = new AccountList();
//        for (Account i : a.getAccountList()) {
//            if (i.getRank() != 0) {
//                model.addRow(new Object[]{i.getUsername(), i.getFullName(), i.getBirthday(), "", "", i.getPhoneNum(),
//                    "", ""});
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneAdmin = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        osearch = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        softaz = new javax.swing.JButton();
        ofullname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        obirthday = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ophonenum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        oemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        osex = new javax.swing.JTextField();
        osex1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        oaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ofb = new javax.swing.JTextField();
        lbPicture = new javax.swing.JLabel();
        softza = new javax.swing.JButton();
        softaz1 = new javax.swing.JButton();
        softaz2 = new javax.swing.JButton();
        jpnView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(650, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        paneAdmin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 54));
        jLabel1.getAccessibleContext().setAccessibleName("");

        jLabel2.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search");
        paneAdmin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 62, -1));

        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt);

        paneAdmin.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 950, 300));

        osearch.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        paneAdmin.add(osearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 190, -1));

        delete.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        paneAdmin.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, -1, -1));

        logout.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        paneAdmin.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 95, -1));
        logout.getAccessibleContext().setAccessibleName("ButtonDX");

        softaz.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        softaz.setText("Sort by username A-Z");
        paneAdmin.add(softaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 160, -1));

        ofullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofullnameActionPerformed(evt);
            }
        });
        paneAdmin.add(ofullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        paneAdmin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 70, -1));

        jLabel4.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Birthday");
        paneAdmin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        obirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obirthdayActionPerformed(evt);
            }
        });
        paneAdmin.add(obirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 200, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone");
        paneAdmin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 70, -1));

        ophonenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ophonenumActionPerformed(evt);
            }
        });
        paneAdmin.add(ophonenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 200, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        paneAdmin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 70, -1));

        oemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oemailActionPerformed(evt);
            }
        });
        paneAdmin.add(oemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 200, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        paneAdmin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 70, -1));

        osex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osexActionPerformed(evt);
            }
        });
        paneAdmin.add(osex, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 200, -1));

        osex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osex1ActionPerformed(evt);
            }
        });
        paneAdmin.add(osex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 200, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Work");
        paneAdmin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 70, -1));

        oaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oaddressActionPerformed(evt);
            }
        });
        paneAdmin.add(oaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 200, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address");
        paneAdmin.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 70, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Facebook");
        paneAdmin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 80, -1));

        ofb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofbActionPerformed(evt);
            }
        });
        paneAdmin.add(ofb, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 200, -1));

        lbPicture.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        paneAdmin.add(lbPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 210, 200));

        softza.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        softza.setText("Sort by name Z-A");
        paneAdmin.add(softza, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 140, -1));

        softaz1.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        softaz1.setText("Sort by username Z-A");
        paneAdmin.add(softaz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 160, -1));

        softaz2.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        softaz2.setText("Sort by name A-Z");
        paneAdmin.add(softaz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 140, -1));

        jpnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiNetbean/Pic/ABSTRACT_BACKGROUND_01.jpg"))); // NOI18N
        paneAdmin.add(jpnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 520));

        getContentPane().add(paneAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        guiMain f1 = new guiMain();
        f1.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
//        final DefaultTableModel model = (DefaultTableModel) jt.getModel();
//        AccountList a = new AccountList();
//        int index = jt.getSelectedRow();
//        if (index == -1) {
//            return;
//        }
//        String choice = (String) jt.getValueAt(index, 0);
//        a.delete(choice);
//        model.removeRow(index);
    }//GEN-LAST:event_deleteActionPerformed

    private void ofullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ofullnameActionPerformed

    private void obirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obirthdayActionPerformed

    private void ophonenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ophonenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ophonenumActionPerformed

    private void oemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oemailActionPerformed

    private void osexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_osexActionPerformed

    private void osex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osex1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_osex1ActionPerformed

    private void oaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oaddressActionPerformed

    private void ofbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ofbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Account a = new Account("fudio101_admin007", "Ng01637202484", "Nguyen Do The Nguyen",
                        LocalDate.of(2001, Month.JANUARY, 1), "0337202484");
                new guiAdmin(a);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jpnView;
    private javax.swing.JTable jt;
    private javax.swing.JLabel lbPicture;
    private javax.swing.JButton logout;
    private javax.swing.JTextField oaddress;
    private javax.swing.JTextField obirthday;
    private javax.swing.JTextField oemail;
    private javax.swing.JTextField ofb;
    private javax.swing.JTextField ofullname;
    private javax.swing.JTextField ophonenum;
    private javax.swing.JTextField osearch;
    private javax.swing.JTextField osex;
    private javax.swing.JTextField osex1;
    private javax.swing.JPanel paneAdmin;
    private javax.swing.JButton softaz;
    private javax.swing.JButton softaz1;
    private javax.swing.JButton softaz2;
    private javax.swing.JButton softza;
    // End of variables declaration//GEN-END:variables
}
