/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiNetbean;

import Encryption.ChuyenManHinhController;
import GUI.GuiAdmin;
import Storage.Account;
import Storage.AccountList;
import java.time.LocalDate;
import java.time.Month;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class guiAdmin extends javax.swing.JFrame {

    JFrame f;

    /**
     * Creates new form guiAdmin
     */
    public guiAdmin(Account login) {
        initComponents();

        setTitle("Admin");


        
        
//        final DefaultTableModel model = (DefaultTableModel) jt.getModel();
//        AccountList a = new AccountList();
//        for (Account i : a.getAccountList()) {
//            if (i.getRank() != 0) {
//                model.addRow(new Object[]{i.getUsername(), i.getFullName(), i.getBirthday(), "", "", i.getPhoneNum(),
//                    "", ""});
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneAdmin = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jtfSearch = new javax.swing.JTextField();
        jpnView = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(650, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        paneAdmin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 11, 285, 54));
        jLabel1.getAccessibleContext().setAccessibleName("");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sorted by");
        paneAdmin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 217, 62, -1));

        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt);

        paneAdmin.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 750, 170));

        btnAdd.setText("add");
        paneAdmin.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        jtfSearch.setText("search");
        paneAdmin.add(jtfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 190, -1));

        jpnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiNetbean/Pic/ABSTRACT_BACKGROUND_01.jpg"))); // NOI18N
        paneAdmin.add(jpnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 520));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        paneAdmin.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 213, -1, -1));

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        paneAdmin.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 11, 95, -1));
        logout.getAccessibleContext().setAccessibleName("ButtonDX");

        getContentPane().add(paneAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        guiMain f1 = new guiMain();
        f1.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
//        final DefaultTableModel model = (DefaultTableModel) jt.getModel();
//        AccountList a = new AccountList();
//        int index = jt.getSelectedRow();
//        if (index == -1) {
//            return;
//        }
//        String choice = (String) jt.getValueAt(index, 0);
//        a.delete(choice);
//        model.removeRow(index);
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Account a = new Account("fudio101_admin007", "Ng01637202484", "Nguyen Do The Nguyen",
                        LocalDate.of(2001, Month.JANUARY, 1), "0337202484");
                new guiAdmin(a);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jpnView;
    private javax.swing.JTable jt;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JButton logout;
    private javax.swing.JPanel paneAdmin;
    // End of variables declaration//GEN-END:variables
}
