/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiNetbean;

import Storage.Account;
import Storage.AccountList;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author phamn
 */
public class guiConfirmInformation extends javax.swing.JFrame {

    /**
     * Creates new form guiConfirmInformation
     */
    public guiConfirmInformation(Account account, Boolean mod) {
        initComponents();
        reset = account;
        mode = mod;
        initCustomer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		usernameLb = new javax.swing.JLabel();
		username = new javax.swing.JTextField();
		nameLb = new javax.swing.JLabel();
		name = new javax.swing.JTextField();
		phoneLb = new javax.swing.JLabel();
		phone = new javax.swing.JTextField();
		birthdaylLb = new javax.swing.JLabel();
		birthday = new com.toedter.calendar.JDateChooser();
		addressLb = new javax.swing.JLabel();
		address = new javax.swing.JTextField();
		workLb = new javax.swing.JLabel();
		work = new javax.swing.JTextField();
		fbLb = new javax.swing.JLabel();
		fb = new javax.swing.JTextField();
		emailLb = new javax.swing.JLabel();
		email = new javax.swing.JTextField();
		jButton = new javax.swing.JButton();
		sexLb = new javax.swing.JLabel();
		sex = new javax.swing.JComboBox<String>();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
		jLabel1.setText("Confirm Information");

		usernameLb.setText("Username");

		nameLb.setText("Fullname");

		phoneLb.setText("Phone");

		birthdaylLb.setText("Date of birth");

		birthday.setDateFormatString("dd/MM/YYYY");
		birthday.setDateFormatString("dd/MM/yyyy");

		addressLb.setText("Address");

		workLb.setText("Work");

		fbLb.setText("Facebook");

		emailLb.setText("Email");

		jButton.setFont(new java.awt.Font("UTM Alberta Heavy", 0, 18)); // NOI18N
		jButton.setText("CONFIRM INFOMATION");
		jButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonActionPerformed(evt);
			}
		});

		sexLb.setText("Sex");

		sex.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Male", "Female" }));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap(111, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addComponent(jLabel1).addGap(97, 97, 97))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(emailLb, javax.swing.GroupLayout.PREFERRED_SIZE,
																78, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(55, 55, 55).addComponent(email,
																javax.swing.GroupLayout.PREFERRED_SIZE, 170,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addComponent(workLb,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 78,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(55, 55, 55).addComponent(work,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 170,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addComponent(addressLb,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 78,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(55, 55, 55).addComponent(address,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 170,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addComponent(fbLb,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 78,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(55, 55, 55).addComponent(fb,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 170,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(sexLb))
												.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(usernameLb,
																javax.swing.GroupLayout.PREFERRED_SIZE, 78,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(nameLb, javax.swing.GroupLayout.PREFERRED_SIZE,
																78, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(phoneLb, javax.swing.GroupLayout.PREFERRED_SIZE,
																78, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(birthdaylLb,
																javax.swing.GroupLayout.PREFERRED_SIZE, 78,
																javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(55, 55, 55)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(sex,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(jPanel1Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(username,
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				170,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(name,
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				170,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(phone,
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				170,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(birthday,
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				170,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))))
												.addGap(120, 120, 120))))
				.addGroup(jPanel1Layout
						.createSequentialGroup().addGap(147, 147, 147).addComponent(jButton,
								javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addGap(45, 45, 45)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(usernameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(nameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(phoneLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(birthdaylLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(sexLb).addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(addressLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(work, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(workLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(fb, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(fbLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(emailLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(44, 44, 44).addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(23, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonActionPerformed
        String un = username.getText();
        String fn = name.getText();
        String pn = phone.getText();
        String ar = address.getText();
        String w = work.getText();
        String f = fb.getText();
        String e = email.getText();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String bd = dateFormat.format(birthday.getDate());
        if (reset.getUsername().equals(un) && reset.getFullName().equals(fn) && reset.getPhoneNum().equals(pn)
                && reset.getSex() == (sex.getSelectedItem() == "Male") && reset.getAddress().equals(ar)
                && reset.getWork().equals(w) && reset.getFb().equals(f) && reset.getEmail().equals(e)
                && reset.getBirthday().equals(bd)) {
            javax.swing.JPasswordField field1 = new javax.swing.JPasswordField();
            field1.setEchoChar('\u2022');
            javax.swing.JPasswordField field2 = new javax.swing.JPasswordField();
            field2.setEchoChar('\u2022');
            Object[] message = {"New password:", field1, "Re-enter new pass:", field2};
            int option = JOptionPane.showConfirmDialog(rootPane, message, "Enter new password",
                    JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                char[] value1 = field1.getPassword();
                char[] value2 = field2.getPassword();
                if ((new String(value1)).equals(new String(value2))) {
                    reset.setNewPassword(new String(value1));
                    new guiMain().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Password incorrect", "Warning",
                            JOptionPane.WARNING_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Confirmation information is not correct", "Warning",
                    JOptionPane.WARNING_MESSAGE);
        }
    }// GEN-LAST:event_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiConfirmInformation.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiConfirmInformation.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiConfirmInformation.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiConfirmInformation.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiConfirmInformation(new AccountList().accountSearch("fudi"), false).setVisible(true);
            }
        });
    }

    private Account reset;
    private Boolean mode;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField address;
	private javax.swing.JLabel addressLb;
	private com.toedter.calendar.JDateChooser birthday;
	private javax.swing.JLabel birthdaylLb;
	private javax.swing.JTextField email;
	private javax.swing.JLabel emailLb;
	private javax.swing.JTextField fb;
	private javax.swing.JLabel fbLb;
	private javax.swing.JButton jButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField name;
	private javax.swing.JLabel nameLb;
	private javax.swing.JTextField phone;
	private javax.swing.JLabel phoneLb;
	private javax.swing.JComboBox<String> sex;
	private javax.swing.JLabel sexLb;
	private javax.swing.JTextField username;
	private javax.swing.JLabel usernameLb;
	private javax.swing.JTextField work;
	private javax.swing.JLabel workLb;
	// End of variables declaration//GEN-END:variables

    private void initCustomer() {
        if (mode) {
            phone.setText(reset.getPhoneNum());
            phone.setEditable(false);
        } else {
            username.setText(reset.getUsername());
            username.setEditable(false);
        }
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.YEAR, 2001);
        cal.set(Calendar.MONTH, 0);
        cal.set(Calendar.DAY_OF_MONTH, 1);
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        Date date = cal.getTime();
        birthday.setDate(date);
//        usernameLb.setVisible(reset.getUsername() != null);
//        username.setVisible(reset.getUsername() != null);
//        nameLb.setVisible(reset.getFullName() != null);
//        name.setVisible(reset.getFullName() != null);
//        phoneLb.setVisible(reset.getPhoneNum() != null);
//        phone.setVisible(reset.getPhoneNum() != null);
//        addressLb.setVisible(reset.getAddress() != null);
//        address.setVisible(reset.getAddress() != null);
//        workLb.setVisible(reset.getWork() != null);
//        work.setVisible(reset.getWork() != null);
//        fbLb.setVisible(reset.getFb() != null);
//        fb.setVisible(reset.getFb() != null);
//        emailLb.setVisible(reset.getEmail() != null);
//        email.setVisible(reset.getEmail() != null);
    }
}
