/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiNetbean;


import Storage.Account;
import javax.swing.JOptionPane;
import java.time.Instant;
import java.time.LocalDate;
import java.time.Month;
import java.time.ZoneId;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Admin
 */
public class guiProfile extends javax.swing.JFrame {

	/**
	 * Creates new form guiLogin
	 * 
	 * @param login_
	 */
	public guiProfile(Account login_) {
		this.login = login_;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        birthday = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        editProfileButton = new javax.swing.JButton();
        agreeButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        email1 = new javax.swing.JTextField();
        email2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GuiNetbean/Pic/4882066.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pic.setBorder(javax.swing.BorderFactory.createTitledBorder("Avatar"));
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 210, 190));

        jLabel2.setFont(new java.awt.Font("UTM Americana EB", 0, 24)); // NOI18N
        jLabel2.setText("PROFILE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        jLabel3.setText("Carrot team @ 2021");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, -1, -1));

        fullname.setText(login.getFullName());
        fullname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fullname.setText("fullname");
        getContentPane().add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 280, -1));

        birthday.setText("birthday");
        birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayActionPerformed(evt);
            }
        });
        getContentPane().add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 140, -1));

        address.setText("address");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 210, 50));

        phone.setText("phone number");
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 210, -1));

        email.setText("fblink");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 190, -1));

        editProfileButton.setText("Edit profile");
        editProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        agreeButton.setText("Agree");
        agreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(agreeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, -1, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));
        getContentPane().add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 160, -1));

        email1.setText("email");
        getContentPane().add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 190, -1));

        email2.setText("word");
        getContentPane().add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 210, 70));

        jLabel4.setText("Facebook link");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 100, -1));

        jLabel5.setText("Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 50, -1));

        jLabel6.setText("Date of birth");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 100, -1));

        jLabel7.setText("Gender");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 100, 20));

        jLabel8.setText("Address   _____________________");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 220, -1));

        jLabel9.setText("Phone number   ________________");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 210, -1));

        jLabel11.setText("Work  ________________________");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 220, -1));

        jLabel12.setText("----------About----------");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 130, -1));

        jLabel13.setText("Email");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 100, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jMenu1.setText("Account");

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayActionPerformed

	Date date = new Date();

	private void phoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_phoneActionPerformed
	}// GEN-LAST:event_phoneActionPerformed

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
		int output = JOptionPane.showConfirmDialog(jMenuItem2, "Do you want to sign out?", "Logout",
				JOptionPane.YES_NO_OPTION);
		if (output == 0) {
			dispose();
		}
	}// GEN-LAST:event_jMenuItem2ActionPerformed

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		int output = JOptionPane.showConfirmDialog(jMenuItem2, "Do you want to sign out?", "Logout",
				JOptionPane.YES_NO_OPTION);
		if (output == 0) {
			guiMain frm1 = new guiMain();
			frm1.setVisible(true);
			dispose();
		}
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	private void editProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editProfileButtonActionPerformed
		agreeButton.setVisible(true);
		cancelButton.setVisible(true);
		editProfileButton.setVisible(false);
		fullname.setEditable(true);
		phone.setEditable(true);
		birthday.setVisible(false);
		// dateChooser.setVisible(true);

	}// GEN-LAST:event_editProfileButtonActionPerformed

	private void agreeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_agreeButtonActionPerformed
		agreeButton.setVisible(false);
		cancelButton.setVisible(false);
		editProfileButton.setVisible(true);
		fullname.setEditable(false);
		phone.setEditable(false);
		birthday.setVisible(true);
		dateChooser.setVisible(false);
		String fullName = fullname.getText();
		String phone_ = phone.getText();
		Date birthday_ = dateChooser.getCalendar().getTime();
//        if (!isValidPhone(phone_)) {
//            JOptionPane.showMessageDialog(agreeButton,
//                    "S? ?i?n tho?i b?n nh?p không ph?i c?a nhà m?ng Vi?t Nam", "InvalidPhoneNumberError",
//                    JOptionPane.WARNING_MESSAGE);
//        } else {
//            if (fullName != login.getFullname()) {
//                login.setFullName(fullName);
//            }
//            if (birthday_ != new Date()) {
//                login.setBirthday(convertToLocalDateViaMilisecond(birthday_));
//            }
//            if (phone_ != login.getPhoneNum()) {
//                login.setPhoneNum(phone_);
//            }
//            AccountList a = new AccountList();
//            a.editAccount(login);
//        }
	}// GEN-LAST:event_agreeButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
		agreeButton.setVisible(false);
		cancelButton.setVisible(false);
		editProfileButton.setVisible(true);
		fullname.setEditable(false);
		phone.setEditable(false);
		birthday.setVisible(true);
		dateChooser.setVisible(false);
	}// GEN-LAST:event_cancelButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;

				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(guiProfile.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);

		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(guiProfile.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);

		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(guiProfile.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);

		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(guiProfile.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Account a = new Account("fudio", "Ng01637202484", "Nguy?n ?? Th? Nguyên",
						LocalDate.of(2001, Month.JANUARY, 1), "0337202484");
				new guiProfile(a).setVisible(true);
			}
		});
	}

	private boolean isValidPhone(String phoneNum) {
		String regex = "(84[3|5|7|8|9]|0[3|5|7|8|9])+([0-9]{8})";
		Pattern p = Pattern.compile(regex);
		Matcher m = p.matcher(phoneNum);
		return m.matches();
	}

	public LocalDate convertToLocalDateViaMilisecond(Date dateToConvert) {
		return Instant.ofEpochMilli(dateToConvert.getTime()).atZone(ZoneId.systemDefault()).toLocalDate();
	}

	private Account login;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton agreeButton;
    private javax.swing.JTextField birthday;
    private javax.swing.JButton cancelButton;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton editProfileButton;
    private javax.swing.JTextField email;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField email2;
    private javax.swing.JTextField fullname;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel pic;
    // End of variables declaration//GEN-END:variables
}
