/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiNetbean;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.swing.ButtonGroup;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.ItemLabelAnchor;
import org.jfree.chart.labels.ItemLabelPosition;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.data.category.DefaultCategoryDataset;

import Storage.AccountList;
import Storage.Statistics;
import java.util.Enumeration;
import javax.swing.AbstractButton;

import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.CategoryItemRenderer;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.chart.ui.TextAnchor;

/**
 *
 * @author theng
 */
public class guiStatisticalChart extends javax.swing.JFrame {

    /**
     * Creates new form guiStatisticalChart
     */
    public guiStatisticalChart() {
        statisticsBy = new ButtonGroup();
        chartStyle = new ButtonGroup();

        Calendar cal = Calendar.getInstance();
        cal.setTime(new Date());
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        now = cal.getTime();

        initComponents();
        createDataset();
        initBarChart(pnChart);
    }

    private void initBarChart(javax.swing.JPanel chartPanel) {
        // Create barChart
        barChart = ChartFactory.createBarChart("Statistical Chart", "Time", "Number of Register", dataset,
                PlotOrientation.VERTICAL, false, true, true);

        CategoryItemRenderer renderer = ((CategoryPlot) barChart.getPlot()).getRenderer();
        renderer.setDefaultItemLabelGenerator(new StandardCategoryItemLabelGenerator());
        renderer.setDefaultItemLabelsVisible(true);
        ItemLabelPosition position = new ItemLabelPosition(ItemLabelAnchor.OUTSIDE12, TextAnchor.TOP_CENTER);
        renderer.setDefaultPositiveItemLabelPosition(position);

        ChartPanel panel = new ChartPanel(barChart);
        panel.setPreferredSize(new Dimension(chartPanel.getWidth(), chartPanel.getHeight()));

        chartPanel.removeAll();
        chartPanel.setLayout(new CardLayout());
        chartPanel.add(panel);
        chartPanel.validate();
        chartPanel.repaint();
    }

    private void initLineChart(javax.swing.JPanel chartPanel) {
        // Create lineChart
        lineChart = ChartFactory.createLineChart("Statistical Chart", // Chart title
                "Time", // X-Axis Label
                "Number of Register", // Y-Axis Label
                dataset, PlotOrientation.VERTICAL, false, true, true);

        CategoryPlot plot = (CategoryPlot) lineChart.getPlot();

        LineAndShapeRenderer renderer = (LineAndShapeRenderer) plot.getRenderer();
        renderer.setDefaultShapesVisible(true);
        DecimalFormat decimalformat1 = new DecimalFormat("##");
        renderer.setDefaultItemLabelGenerator(new StandardCategoryItemLabelGenerator("{2}", decimalformat1));
        renderer.setDefaultItemLabelsVisible(true);
        renderer.setDefaultSeriesVisible(true);

        ChartPanel panel = new ChartPanel(lineChart);
        panel.setPreferredSize(new Dimension(840, 450));
        panel.setPreferredSize(new Dimension(chartPanel.getWidth(), chartPanel.getHeight()));

        chartPanel.removeAll();
        chartPanel.setLayout(new CardLayout());
        chartPanel.add(panel);
        chartPanel.validate();
        chartPanel.repaint();
    }

    private void createDataset() {
        AccountList list = new AccountList();
        listItem = list.getStatitical();
        dataset = new DefaultCategoryDataset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnRoot = new javax.swing.JPanel();
        pnOption = new javax.swing.JPanel();
        pnDay = new javax.swing.JPanel();
        fromLabel = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        toLabel = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        statisticsByLabel1 = new javax.swing.JLabel();
        allTimeButton = new javax.swing.JRadioButton();
        betweenButton = new javax.swing.JRadioButton();
        chartStyleLabel = new javax.swing.JLabel();
        barChartButton = new javax.swing.JRadioButton();
        lineChartButton = new javax.swing.JRadioButton();
        showButton = new javax.swing.JButton();
        pnChart = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fromLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fromLabel.setText("From");
        fromLabel.setToolTipText("");

        jDateChooser.setDate(now);

        toLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        toLabel.setText("to");
        toLabel.setToolTipText("");

        jDateChooser1.setDate(now);

        javax.swing.GroupLayout pnDayLayout = new javax.swing.GroupLayout(pnDay);
        pnDay.setLayout(pnDayLayout);
        pnDayLayout.setHorizontalGroup(
            pnDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromLabel)
                    .addComponent(toLabel))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnDayLayout.setVerticalGroup(
            pnDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDayLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(fromLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(toLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jDateChooser.setVisible(false);
        jDateChooser1.setVisible(false);
        fromLabel.setVisible(false);
        toLabel.setVisible(false);

        statisticsByLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statisticsByLabel1.setText("Statistics by:");
        statisticsByLabel1.setToolTipText("");

        statisticsBy.add(allTimeButton);
        allTimeButton.setSelected(true);
        allTimeButton.setText("All time");
        allTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTimeButtonActionPerformed(evt);
            }
        });

        statisticsBy.add(betweenButton);
        betweenButton.setText("Between");
        betweenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betweenButtonActionPerformed(evt);
            }
        });

        chartStyleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chartStyleLabel.setText("Chart style:");
        chartStyleLabel.setToolTipText("");

        barChartButton.setSelected(true);
        barChartButton.setText("Bar chart");
        barChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barChartButtonActionPerformed(evt);
            }
        });

        lineChartButton.setText("Line chart");
        lineChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineChartButtonActionPerformed(evt);
            }
        });

        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnOptionLayout = new javax.swing.GroupLayout(pnOption);
        pnOption.setLayout(pnOptionLayout);
        pnOptionLayout.setHorizontalGroup(
            pnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnOptionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statisticsByLabel1)
                    .addComponent(allTimeButton)
                    .addComponent(betweenButton)
                    .addComponent(chartStyleLabel)
                    .addComponent(barChartButton)
                    .addComponent(lineChartButton)
                    .addComponent(showButton)))
        );
        pnOptionLayout.setVerticalGroup(
            pnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOptionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(statisticsByLabel1)
                .addGap(13, 13, 13)
                .addComponent(allTimeButton)
                .addGap(7, 7, 7)
                .addGroup(pnOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnOptionLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pnDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(betweenButton))
                .addComponent(chartStyleLabel)
                .addGap(13, 13, 13)
                .addComponent(barChartButton)
                .addGap(7, 7, 7)
                .addComponent(lineChartButton)
                .addGap(27, 27, 27)
                .addComponent(showButton))
        );

        statisticsBy.add(betweenButton);
        chartStyle.add(barChartButton);
        statisticsBy.add(betweenButton);
        chartStyle.add(lineChartButton);

        javax.swing.GroupLayout pnChartLayout = new javax.swing.GroupLayout(pnChart);
        pnChart.setLayout(pnChartLayout);
        pnChartLayout.setHorizontalGroup(
            pnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        pnChartLayout.setVerticalGroup(
            pnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnRootLayout = new javax.swing.GroupLayout(pnRoot);
        pnRoot.setLayout(pnRootLayout);
        pnRootLayout.setHorizontalGroup(
            pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRootLayout.createSequentialGroup()
                .addComponent(pnOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnRootLayout.setVerticalGroup(
            pnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_allTimeButtonActionPerformed
        jDateChooser.setVisible(false);
//        jDateChooser1.setVisible(false);
        fromLabel.setVisible(false);
        toLabel.setVisible(false);
    }// GEN-LAST:event_allTimeButtonActionPerformed

    private void betweenButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_betweenButtonActionPerformed
        jDateChooser.setVisible(true);
//        jDateChooser1.setVisible(true);
        fromLabel.setVisible(true);
        toLabel.setVisible(true);
    }// GEN-LAST:event_betweenButtonActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showButtonActionPerformed
        String select = getSelectedStatisticsBy(statisticsBy);
        switch (select) {
            case "All time":
                setAllTime();
                break;
            case "Between":
                setBetweenTime();
                break;
        }
    }// GEN-LAST:event_showButtonActionPerformed

    public String getSelectedStatisticsBy(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    private void lineChartButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_lineChartButtonActionPerformed
        initLineChart(pnChart);
    }// GEN-LAST:event_lineChartButtonActionPerformed

    private void barChartButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_barChartButtonActionPerformed
        initBarChart(pnChart);
    }// GEN-LAST:event_barChartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiStatisticalChart.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiStatisticalChart.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiStatisticalChart.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiStatisticalChart.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new guiStatisticalChart().setVisible(true);
                guiStatisticalChart example = new guiStatisticalChart();
//                example.setAlwaysOnTop(true);
                example.setVisible(true);
            }
        });
    }

    private JFreeChart barChart;
    private JFreeChart lineChart;
    private final ButtonGroup statisticsBy;
    private final ButtonGroup chartStyle;
    DefaultCategoryDataset dataset;
    List<Statistics> listItem;
    private final Date now;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allTimeButton;
    private javax.swing.JRadioButton barChartButton;
    private javax.swing.JRadioButton betweenButton;
    private javax.swing.JLabel chartStyleLabel;
    private javax.swing.JLabel fromLabel;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JRadioButton lineChartButton;
    private javax.swing.JPanel pnChart;
    private javax.swing.JPanel pnDay;
    private javax.swing.JPanel pnOption;
    private javax.swing.JPanel pnRoot;
    private javax.swing.JButton showButton;
    private javax.swing.JLabel statisticsByLabel1;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables

    private void setAllTime() {
        for (Statistics i : listItem) {
            dataset.addValue(i.getCount(), "", i.getCreateDate());
        }
    }

    private void setBetweenTime() {
        dataset.clear();
        for (Statistics i : listItem) {
            Date t = i.getCreateDate();
            long time = t.getTime();
            long time1 = getTime_(jDateChooser).getTime();
            System.out.println(jDateChooser.getDate());
//            long time2 = getTime_(jDateChooser1).getTime();
            if (time >= time1 ) {
                dataset.addValue(i.getCount(), "", t);
            }
        }
    }
    private Date getTime_(com.toedter.calendar.JDateChooser jDateChooser){
        Date value;
        Calendar cal = Calendar.getInstance();
        Date temp = jDateChooser.getDate();
        if (temp==null)
        	return null;
        cal.setTime(temp);
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        value = cal.getTime();
        return value;
    }

}
